import { StyleSheet } from 'react-native';

const style = StyleSheet.create({
  codeContainer: {
    flexDirection: 'row',
    top: 15,
    left: 35,
    gap: 12,
    width: 328,
    height: 56,
  },
  container: {
    padding: 20,
    gap: 10,
    marginRight: 10,
  },
  image: {
    marginTop: 22,
  },
  otpInput: {
    textAlign: 'center',
    fontSize: 32,
    fontWeight: '100',
    width: 56,
    height: 56,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderRadius: 8,
    paddingBottom: 7,
    color: '#000B0F',
  },
  wrongInput: {
    textAlign: 'center',
    alignItems: 'center',
    fontSize: 32,
    fontWeight: '500',
    width: 56,
    height: 56,
    backgroundColor: '#FFFFFF',
    borderColor: '#ED3237',
    borderWidth: 1,
    borderRadius: 8,
    paddingBottom: 7,
    color: '#000B0F',
  },
  activeInput: {
    borderColor: '#BCD848',
  },
  wrap: {
    alignItems: 'center',
    textAlign: 'center',
    marginTop: 40,
  },
  emailContent: {
    fontSize: 16,
    color: '#006B3F',
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
    fontWeight: '500',
    alignItems: 'center',
    opacity: 0.78,
  },
  resendText: {
    fontSize: 16,
    color: '#006B3F',
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
    fontWeight: '500',
    alignItems: 'center',
    bottom: 19,
    opacity: 0.78,
  },
  errorResendText: {
    fontSize: 16,
    color: '#006B3F',
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
    fontWeight: '500',
    alignItems: 'center',
    top: 39,
    opacity: 0.78,
  },
  text: {
    fontSize: 16,
    color: '#001E28',
    fontWeight: '200',
    width: 372,
    height: 42,
    textAlign: 'center',
    marginTop: 40,
  },
  msg: {
    fontSize: 16,
    color: '#001E28',
    fontWeight: '200',
    width: 372,
    height: 42,
    textAlign: 'center',
    marginTop: 25,
  },

  buttonResend: {
    textAlign: 'center',
    marginBottom: 60,
  },
  blurText: {
    fontSize: 16,
    color: '#545454',
    fontWeight: '400',
    width: 372,
    height: 42,
    textAlign: 'center',
    opacity: 0.7,
    marginTop: 40,
  },
  verifyText: {
    fontFamily: 'Poppins',
    fontSize: 22,
    fontWeight: '500',
    color: '#000BOF',
    top: 45,
  },
  arrowPointer: {
    top: 24,
    width: 28,
    height: 28,
  },
  button: {
    backgroundColor: '#006B3F',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginVertical: 10,
    alignItems: 'center',
    height: 64,
    marginTop: 20,
  },
  buttonText: {
    fontWeight: '600',
    color: '#f1f1f1',
    fontSize: 13,
    borderColor: '#545454',
    borderRadius: 4,
    borderTopStartRadius: 0.5,
    paddingTop: 10,
    fontFamily: 'Roboto',
  },
  buttonNotReady: {
    backgroundColor: '#006B3F',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 20,
    height: 64,
    opacity: 0.4,
  },
  errorMsg: {
    color: '#C54B4F',
    fontSize: 14,
    fontWeight: 500,
    fontFamily: 'Roboto',
    textAlign: 'center',
    opacity: 0.75,
    top: 27,
    left: 2,
  },
  inputFocused: {
    borderColor: '#BCD848',
  },
  modalView: {
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.59)', // semi-transparent overlay
  },
  modalContent: {
    alignItems: 'center',
    textAlign: 'center',
    backgroundColor: '#F5F5F7',
    borderRadius: 12,
    width: '90%',
    height: 307,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  confirmTxt: {
    color: '#000B0F',
    fontSize: 22,
    fontWeight: 500,
    top: 21,
  },
  modalButton: {
    backgroundColor: '#006B3F',
    paddingVertical: 12,
    paddingHorizontal: 120,
    borderRadius: 10,
    marginVertical: 10,
    alignItems: 'center',
    height: 64,
    marginTop: 40,
  },
  modalButtonText: {
    fontWeight: '600',
    color: '#f1f1f1',
    fontSize: 13,
    borderColor: '#545454',
    borderRadius: 4,
    borderTopStartRadius: 0.5,
    paddingTop: 10,
    fontFamily: 'Roboto',
  },
});

export default style;
