import { StyleSheet } from 'react-native';

const style = StyleSheet.create({
  container: {
    top: 48,
    fontSize: 2,
    flex: 1,
    left: 30,
    marginRight: 65,
    gap: 1,
  },
  arrowPointer: {
    bottom: 14,
    width: 28,
    height: 28,
  },
  text: {
    fontSize: 16,
    fontWeight: '500',
    color: '#000B0F',
    fontFamily: 'Roboto',
  },
  headerText: {
    fontSize: 24,
    opacity: 0.9,
    fontWeight: '500',
    color: '#000000',
    fontFamily: 'Roboto',
    top: 10,
    marginBottom: 10,
  },
  subHeader: {
    fontSize: 14,
    opacity: 0.6,
    fontWeight: 'bold',
    color: '#000000',
    fontFamily: 'Roboto',
    top: 10,
    marginBottom: 5,
  },

  dateTxt: {
    fontSize: 14,
    fontWeight: '400',
    color: '#545454',
    fontFamily: 'Roboto',
    opacity: 0.8,
  },
  updateTxt: {
    fontSize: 14,
    fontWeight: '500',
    color: '#000000',
    fontFamily: 'Roboto',
  },
  termsText: {
    top: 20,
    fontFamily: 'Roboto',
    fontSize: 14,
    color: '#001E28',
    opacity: 0.8,
    fontWeight: '400',
    lineHeight: 14,
    letterSpacing: 0.2,
    paddingBottom: 20,
  },
  checkboxTxt: {
    fontFamily: 'Roboto',
    fontSize: 15,
    color: '#001E28',
    opacity: 0.8,
    fontWeight: '400',
    letterSpacing: 0.2,
  },
  proceedText: {
    color: '#f1f1f1',
    fontSize: 13,
    fontWeight: 500,
    borderColor: '#545454',
    borderRadius: 4,
    borderTopStartRadius: 0.5,
    paddingTop: 10,
    fontFamily: 'Roboto',
  },
  checkboxContainer: {
    width: 16,
    height: 16,
    bottom: 6.5,
    borderWidth: 2,
    borderColor: '#757575',
    backgroundColor: '#FFFFFF',
  },
  checkBoxContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    paddingRight: 20,
  },
  checkedBox: {
    backgroundColor: '#0978c8ff',
    borderColor: '#0978c8ff',
  },
  checkBox: {
    justifyContent: 'center',
    flex: 1,
    marginTop: 20,
  },
  tick: {
    color: '#f1f1f1',
    alignItems: 'center',
    top: 2,
    left: 0.5,
  },
  buttonNotReady: {
    backgroundColor: '#006B3F',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 20,
    height: 64,
    opacity: 0.4,
  },
  button: {
    backgroundColor: '#00683F',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 20,
    width: 'auto',
    gap: 48,
    height: 62,
  },
});

export default style;
