import { StyleSheet } from 'react-native';

const style = StyleSheet.create({
  welcomeText: {
    fontFamily: 'Avenir',
    width: 364,
    fontWeight: 500,
    fontSize: 32,
    top: 15,
    left: 7,
  },
  textCode: {
    fontWeight: 400,
    fontSize: 14,
    width: 264,
    height: 19,
  },
  intro: {
    fontFamily: 'Avenir',
    width: 364,
    fontWeight: 400,
    fontSize: 16,
    top: 22,
    left: 7,
    color: '#001E28',
    lineHeight: '100%',
    letterSpacing: 0,
  },
  inputContainer: {
    position: 'relative',
    marginVertical: 20,
    top: 200,
  },
  label: {
    position: 'absolute',
    top: -22,
    left: 10,
    fontSize: 16,
    color: '#001E28',
    backgroundColor: 'white',
    paddingHorizontal: 4,
    zIndex: 1,
    fontWeight: 500,
  },
  bvnInput: {
    borderWidth: 1,
    borderColor: '#ccc',
    padding: 10,
    paddingTop: 16,
    borderRadius: 6,
    fontSize: 16,
  },
  emailInput: {
    borderWidth: 1,
    borderColor: '#ccc',
    padding: 10,
    paddingTop: 16,
    borderRadius: 6,
    fontSize: 16,
  },
  button: {
    backgroundColor: '#00683F',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
    marginLeft: 10,
    marginRight: 35,
    width: 'auto',
    gap: 48,
    height: 62,
    top: 10,
  },

  buttonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 500,
    alignItems: 'center',
    fontStyle: 'medium',
    paddingTop: 10,
    fontFamily: 'Avenir',
  },
  buttonNotReady: {
    backgroundColor: '#ffffff',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
    marginLeft: 10,
    marginRight: 35,
    width: 'auto',
    gap: 48,
    height: 62,
    top: 10,
  },
  buttonNotReadyText: {
    buttonText: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: 500,
      alignItems: 'center',
      fontStyle: 'medium',
      paddingTop: 10,
      fontFamily: 'Avenir',
    },
  },
});

export default style;
