import { StyleSheet } from 'react-native';

const style = StyleSheet.create({
  container: { top: 32, left: 24 },
  welcomeText: {
    fontFamily: 'Roboto',
    width: 364,
    fontWeight: 500,
    fontSize: 28,
    top: 15,
    opacity: 0.8,
  },
  inputContainer: {
    top: 62,
    gap: 31,
  },
  bvnInputContainer: {
    gap: 6,
    bottom: 5,
  },
  emailInputContainer: {
    gap: 12,
    bottom: 5,
  },
  numberContainer: {
    gap: 12,
    bottom: 5,
  },
  textCode: {
    fontWeight: 400,
    fontSize: 14,
    color: '#545454',
    opacity: 0.65,
  },
  intro: {
    opacity: 0.7,
    fontFamily: 'Avenir',
    width: 364,
    height: 63,
    fontWeight: 400,
    fontSize: 14,
    top: 22,
    color: '#001E28',
    lineHeight: '100%',
    letterSpacing: 0,
  },
  labelNumber: {
    position: 'absolute',
    fontSize: 16,
    color: '#001E28',
    paddingHorizontal: 4,
    zIndex: 1,
    fontWeight: 500,
    bottom: 40,
  },
  labelBvn: {
    position: 'absolute',
    fontSize: 16,
    color: '#001E28',
    paddingHorizontal: 4,
    zIndex: 1,
    fontWeight: 500,
    bottom: 65,
  },
  labelEmail: {
    position: 'absolute',
    fontSize: 16,
    color: '#001E28',
    paddingHorizontal: 4,
    zIndex: 1,
    fontWeight: 500,
    bottom: 40,
  },
  textInput: {
    borderBottomWidth: 1,
    borderBottomColor: '#D8D8D8',
    padding: 10,
    paddingTop: 16,
    borderRadius: 0,
    fontSize: 16,
    alignItems: 'center',
  },
  accountButton: {
    backgroundColor: '#f1f1f1',
    borderColor: '#545454',
    borderRadius: 4,
    width: 167,
    height: 48,
    bottom: 16,
    paddingVertical: 5,
    borderWidth: 1,
  },
  button: {
    backgroundColor: '#00683F',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
    marginRight: 60,
    width: 'auto',
    height: 62,
    top: 0,
  },
  buttonText: {
    color: '#545454',
    fontSize: 13,
    fontWeight: 500,
    textAlign: 'center',
    borderColor: '#545454',
    borderRadius: 4,
    paddingTop: 10,
    fontFamily: 'Roboto',
  },
  proceedText: {
    color: '#f1f1f1',
    fontSize: 13,
    fontWeight: 500,
    borderColor: '#545454',
    borderRadius: 4,
    borderTopStartRadius: 0.5,
    paddingTop: 10,
    fontFamily: 'Roboto',
  },
  buttonNotReady: {
    backgroundColor: '#006B3F',
    overlayColor: '#f1f1f1',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    textDecorationStyle: 'solid',
    marginTop: 10,
    marginRight: 60,
    width: 'auto',
    gap: 48,
    height: 62,
    top: 10,
    opacity: 0.6,
  },
  accountText: {
    bottom: 9,
    alignItems: 'center',
  },
  buttonNotReadyText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 500,
    alignItems: 'center',
    fontStyle: 'medium',
    paddingTop: 10,
    fontFamily: 'Avenir',
  },
  buttonsContainer: {
    flexWrap: 'wrap',
    flexDirection: 'row',
    gap: 20,
    top: 10,
  },
  activeButton: {
    backgroundColor: '#00683F',
    borderColor: '#545454',
    borderRadius: 4,
    width: 167,
    height: 48,
    bottom: 16,
    paddingVertical: 5,
    borderWidth: 1,
  },
  activebuttonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: 500,
    textAlign: 'center',
    borderColor: '#545454',
    borderRadius: 4,
    paddingTop: 10,
    fontFamily: 'Roboto',
  },
});

export default style;
